name: Node.js CI

on:
  push:
    paths: [ "package.json" ]
  workflow_dispatch:
    inputs:
      cli:
        description: ' Perintah yang akan di execute(*´ω｀*)'
        type: string
        required: true
        default: 'yarn run start'
      repeat:
        description: ' Ulangi perintah (jika berhasil)'
        type: boolean
        required: true
        default: true

permissions:
  actions: write
  contents: write

jobs:
  setup:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Git config
      run: |
        git config user.name "${{ github.repository_owner }}"
        git config user.email "${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run setup
      run: yarn install && git add yarn.lock && git commit -m "dependencies update" && git pull origin && git push origin
  
  run-script:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Git config
      run: |
        git config user.name "${{ github.repository_owner }}"
        git config user.email "${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Discord config
      run: |
        if [ ${{ github.ref }} = 'refs/heads/main' ]
        then
          echo "secrets.DISCORD_ID=${{ secrets.MAIN_DISCORD_ID }} >> $GITHUB_ENV
          echo "secrets.DISCORD_TOKEN=${{ secrets.MAIN_DISCORD_TOKEN }} >> $GITHUB_ENV
        elif [ ${{ github.ref }} = 'refs/heads/dev' ]
        then
          echo "secrets.DISCORD_ID=${{ secrets.DEV_DISCORD_ID }} >> $GITHUB_ENV
          echo "secrets.DISCORD_TOKEN=${{ secrets.DEV_DISCORD_TOKEN }} >> $GITHUB_ENV
        fi
    - name: Run script
      id: run-script
      run: yarn install && ${{ inputs.cli }}
    - name: Continue workflow
      if: ${{ (inputs.repeat == true) && (steps.run-script.conclusion == 'success') }}
      run: |
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/workflows/node.yml/dispatches -d '{"ref":"${{ github.ref_name }}","inputs":{}}'
