name: Node.js CI

on:
  push:
    paths: [ "package.json" ]
  workflow_dispatch:
    inputs:
      cli:
        description: Input command yang mau di execute disini(*´ω｀*)
        type: string
        required: true
        default: yarn run start
      repeat:
        description: Command yang mau diulang terus menerus?
        type: boolean
        required: true
        default: true

permissions:
  contents: write

jobs:
  setup:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Git config
      run: |
        git config user.name "${{ github.repository_owner }}"
        git config user.email "${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run setup
      run: yarn install && git add yarn.lock && git commit -m "dependencies update" && git pull origin && git push origin
